### ISSUE TITLE
无法正常判断

### ISSUE THREAD

**Issue by moniang** [shanhuijie/GoWatch#1]
没有办法正常判断胜负。。。。

**Comment by shanhuijie** [comment]
AddCoordinat()是添加棋子的函数，如果是连成5颗则返回true自带棋子坐标和棋子颜色。

**Comment by moniang** [comment]
啊，我知道如此。
`chess := ai.Coordinat{}
		chess.Color = 1
		chess.X = validate.Int(s[0])
		chess.Y = validate.Int(s[1])
		xx, x := c.AddCoordinat(chess)
		fmt.Println(xx, x)`
但是，5子连起来，是没有判断胜的

**Comment by shanhuijie** [comment]
这个函数功能主要就是判断五子连心的算法，不是真实的五子棋游戏，请见谅!

**Comment by moniang** [comment]
好的，谢谢
